//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Service.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Afip no esta funcionando en este momento, intente nuevamente mas tarde.
        /// </summary>
        internal static string AfipError {
            get {
                return ResourceManager.GetString("AfipError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Afip funciona correctamente.
        /// </summary>
        internal static string AfipOk {
            get {
                return ResourceManager.GetString("AfipOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El alumno ya esta inscripto para rendir esta materia en el turno indiciado.
        /// </summary>
        internal static string AlreadyEnrolledStudent {
            get {
                return ResourceManager.GetString("AlreadyEnrolledStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inscripción HABILITADA para esta materia en este turno.
        /// </summary>
        internal static string AvailableInscription {
            get {
                return ResourceManager.GetString("AvailableInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionarse una cuenta destino para agregar.
        /// </summary>
        internal static string BackAccountIdNull {
            get {
                return ResourceManager.GetString("BackAccountIdNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede modificar el sujeto de facturación porque está adherido a un débito automático..
        /// </summary>
        internal static string BillingSubjectLockedByAutomaticDebit {
            get {
                return ResourceManager.GetString("BillingSubjectLockedByAutomaticDebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El documento no puede estar en blanco.
        /// </summary>
        internal static string BlankDocument {
            get {
                return ResourceManager.GetString("BlankDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inscripción DESHABILITADA porque el turno no permite incribirse en condición de libre.
        /// </summary>
        internal static string CantTakeExamAsFree {
            get {
                return ResourceManager.GetString("CantTakeExamAsFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inscripción DESHABILITADA porque no es posible inscribirse como libre luego de haber cursado la materia como regular. Debe anotarse nuevamente a la materia como libre.
        /// </summary>
        internal static string CantTakeExamAsFreeAfterRegular {
            get {
                return ResourceManager.GetString("CantTakeExamAsFreeAfterRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe tener una caja abierta para agregar ese medio de pago.
        /// </summary>
        internal static string CashRegisterOpen {
            get {
                return ResourceManager.GetString("CashRegisterOpen", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a El cheque solo puede ser utilizado una vez.
        /// </summary>
        internal static string CheckCanOnlyUsedOnce
        {
            get
            {
                return ResourceManager.GetString("CheckCanOnlyUsedOnce", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionarse un cheque para agregar.
        /// </summary>
        internal static string CheckIdNull {
            get {
                return ResourceManager.GetString("CheckIdNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inscripción DESAHABILITADA para esta materia en este turno ya que tiene correlativas no aprovadas de años anteriores.
        /// </summary>
        internal static string CorrelativeProblem {
            get {
                return ResourceManager.GetString("CorrelativeProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inscripción DESHABILITADA por no estar en el periodo de inscripción..
        /// </summary>
        internal static string DisablePeriodInscription {
            get {
                return ResourceManager.GetString("DisablePeriodInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La persona no tiene cargado un email.
        /// </summary>
        internal static string EmailNotSet {
            get {
                return ResourceManager.GetString("EmailNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inscripción DESHABILITADA porque la mesa no permite incribirse en condición de libre.
        /// </summary>
        internal static string ExamTableDoesNotAcceptFreeStudents {
            get {
                return ResourceManager.GetString("ExamTableDoesNotAcceptFreeStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inscripción DESHABILITADA porque la mesa no permite incribirse en condición de regular.
        /// </summary>
        internal static string ExamTableDoesNotAcceptRegularStudents {
            get {
                return ResourceManager.GetString("ExamTableDoesNotAcceptRegularStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La mesa seleccionada tiene el cupo completo.
        /// </summary>
        internal static string FullExamDesk {
            get {
                return ResourceManager.GetString("FullExamDesk", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a La materia seleccionada tiene el cupo completo.
        /// </summary>
        internal static string FullSubjectExamDesk
        {
            get
            {
                return ResourceManager.GetString("FullSubjectExamDesk", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionarse un fondo a rendir para agregar.
        /// </summary>
        internal static string FundToPayIdNull {
            get {
                return ResourceManager.GetString("FundToPayIdNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inscripción DESHABILITADA para esta materia en este turno debido a que la fecha del examen ya paso.
        /// </summary>
        internal static string InscriptionDateOff {
            get {
                return ResourceManager.GetString("InscriptionDateOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La materia en condición de libre no puede ser rendida en el mismo ciclo lectivo que se curso.
        /// </summary>
        internal static string InscriptionSameSchoolYear {
            get {
                return ResourceManager.GetString("InscriptionSameSchoolYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para visualizar la condición debe cargar las fechas del proximo turno de examen.
        /// </summary>
        internal static string NotAvailableCondition {
            get {
                return ResourceManager.GetString("NotAvailableCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inscripción DESHABILITADA para esta materia debido a que no se encuentra un turno actual o proximo cargado.
        /// </summary>
        internal static string NotCurrentOrNextExamTurn {
            get {
                return ResourceManager.GetString("NotCurrentOrNextExamTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin matricula.
        /// </summary>
        internal static string NotEnrollmentFound {
            get {
                return ResourceManager.GetString("NotEnrollmentFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inscripción DESHABILITADA para esta materia en este turno debido a que no se ha asignado una mesa de exámen a la materia.
        /// </summary>
        internal static string NotExamDesk {
            get {
                return ResourceManager.GetString("NotExamDesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No  inscripto en ningun curso.
        /// </summary>
        internal static string NotPrincipalTurnGradeInscriptionFound {
            get {
                return ResourceManager.GetString("NotPrincipalTurnGradeInscriptionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La novedad no se puede asignar porque el total negativo y es superior al total de la actividad.
        /// </summary>
        internal static string NoveltyEnrollmentNegative {
            get {
                return ResourceManager.GetString("NoveltyEnrollmentNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo se permite ingresar números..
        /// </summary>
        internal static string OnlyNumbers {
            get {
                return ResourceManager.GetString("OnlyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe pase generado.
        /// </summary>
        internal static string PassGeneratedFound {
            get {
                return ResourceManager.GetString("PassGeneratedFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un medio de pago para agregar.
        /// </summary>
        internal static string PaymentChannel {
            get {
                return ResourceManager.GetString("PaymentChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El medio de pago para agregar ya fue añadido previamente.
        /// </summary>
        internal static string PaymentChannelAlreadyAdded {
            get {
                return ResourceManager.GetString("PaymentChannelAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} es requerido.
        /// </summary>
        internal static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inscripción DESHABILITADA para esta materia en este turno ya que es una materia cursada en el mismo ciclo lectivo que el turno activo..
        /// </summary>
        internal static string SameSchoolYearExamTurn {
            get {
                return ResourceManager.GetString("SameSchoolYearExamTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El mail no se envió.
        /// </summary>
        internal static string SentEmailError {
            get {
                return ResourceManager.GetString("SentEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El mail se envió correctamente.
        /// </summary>
        internal static string SentEmailOK {
            get {
                return ResourceManager.GetString("SentEmailOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} no puede contener más de {1} caracteres.
        /// </summary>
        internal static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inscripción DESHABILITADA por tener deuda de cuotas.
        /// </summary>
        internal static string StudentWithDebt {
            get {
                return ResourceManager.GetString("StudentWithDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inscripción DESHABILITADA para esta materia en este turno ya que es una tercer materia desaprobada, cursada en este ciclo lectivo..
        /// </summary>
        internal static string ThirdSubjectLockedTurn {
            get {
                return ResourceManager.GetString("ThirdSubjectLockedTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El total del cheque no puede ser mayor al disponible.
        /// </summary>
        internal static string TotalCheckNotOk {
            get {
                return ResourceManager.GetString("TotalCheckNotOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El total del fondo a rendir no puede ser mayor al disponible.
        /// </summary>
        internal static string TotalFundToPayNotOk {
            get {
                return ResourceManager.GetString("TotalFundToPayNotOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El total no puede ser menor a 0.
        /// </summary>
        internal static string TotalLessThanZero {
            get {
                return ResourceManager.GetString("TotalLessThanZero", resourceCulture);
            }
        }

        internal static string InscriptionOutOfDate
        {
            get
            {
                return ResourceManager.GetString("InscriptionOutOfDate", resourceCulture);
            }
        }
    }
}
